version: '3.8'

services:
  # Broker 1
  kafka-broker-1:
    image: confluentinc/cp-kafka:7.8.0
    container_name: kafka-broker-1
    ports:
      - "9092:9092"
      - "9093:9093"
      - "19093:19093"

    #command: ["tail", "-f", "/dev/null"] # Usado apenas para configurar o cluster
    command: ["kafka-server-start", "/etc/kafka/kraft/broker.properties"]

    volumes:
      - broker1_log_dirs:/tmp
      - broker1_config:/etc/kafka
      - ./broker.properties:/etc/kafka/kraft/broker.properties


  # Kafka UI
  kafka-ui:
    image: provectuslabs/kafka-ui:v0.7.2
    container_name: kafka-ui
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: "Cluster Kafka"
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "10.0.1.10:9092,10.0.1.20:9092,10.0.1.30:9092"
      KAFKA_CLUSTERS_0_PROPERTIES_AUTO_CREATE_TOPICS_ENABLE: "true"

volumes:
  broker1_log_dirs:
  broker1_config:

