# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.92.2
    hooks:
    - id: terraform_fmt
      args:
        - --args=-recursive

    - id: terraform_validate
