version: '3.8'

services:

  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.2
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    volumes:
      - zookeeper_data:/var/lib/zookeeper/data
      - zookeeper_log:/var/lib/zookeeper/log


  kafka-broker-1:
    image: confluentinc/cp-kafka:7.3.2
    container_name: kafka-broker-1
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "19092:19092"
    environment:
      KAFKA_BROKER_ID: 1 
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181 
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:19092 
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-broker-1:9092,EXTERNAL://localhost:19092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2 
      KAFKA_NUM_PARTITIONS: 3 
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true" 
      KAFKA_DELETE_TOPIC_ENABLE: "true" 
      
      #KAFKA_HEAP_OPTS: "-Xmx512M -Xms512M" 

    volumes:
      - broker1_data:/var/lib/kafka/data
  kafka-broker-2:
    image: confluentinc/cp-kafka:7.3.2
    container_name: kafka-broker-2
    depends_on:
      - zookeeper
    ports:
      - "9093:9092"
      - "19093:19093" 
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9093,EXTERNAL://0.0.0.0:19093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-broker-2:9093,EXTERNAL://localhost:19093
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_DELETE_TOPIC_ENABLE: "true"

    volumes:
      - broker2_data:/var/lib/kafka/data

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    depends_on:
      - kafka-broker-1
      - kafka-broker-2
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: "Local-Confluent"
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "kafka-broker-1:9092,kafka-broker-2:9092"
      KAFKA_CLUSTERS_0_PROPERTIES_AUTO_CREATE_TOPICS_ENABLE: "true"

volumes:
  zookeeper_data:
  zookeeper_log:
  broker1_data:
  broker2_data:
